# action.yml
name: "Greet 
description: 'Greet someone and record the time'
inputs:
  greeting:
    description: "Greeting"
    default: "Hello"
  name:
    description: "Who to greet"
    default: "Thanh"
outputs:
  greeting-text:
    description: "Greeting text"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.greeting }}
    - ${{ inputs.name }}
