name: Greet user action
description: Say hello and goodbye to someone

inputs:
  greeting:
    description: "Greeting words"
    required: true
    type: string
  name:
    description: "Someone's name"
    required: true
    type: string
outputs:
  full-greeting:
    value: ${{steps.last-step.outputs.result}}

runs:
  using: "composite"
  steps:
    - name: Say hello
      run: echo "${{inputs.greeting}}, ${{inputs.name}}!"
      shell: bash
    - name: Ask how are you
      run: echo "How are you today, ${{inputs.name}}?"
      shell: bash
    - name: Say goodbye
      run: echo "Have a good day!"
      shell: bash
    - name: Generate output
      id: last-step
      env:
        RESULT: "${{inputs.greeting}}, ${{inputs.name}}!"
      run: echo "result=$(echo $RESULT)" >> $GITHUB_OUTPUT
      shell: bash
