name: Test reuseable workflow - USERNAME
run-name: Test reuseable workflow - USERNAME

on:
  workflow_dispatch:

jobs:
  call-greeting-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    # uses: ./.github/workflows/reusable-workflow.yml@main
    # uses: ./.github/workflows/reusable-workflow.yml@v1
    # uses: ./.github/workflows/reusable-workflow.yml@SHA
    with:
      greeting: "Good morning"
      name: "My friend"
  another-job:
    runs-on: ubuntu-latest
    steps:
      - name: another step
        run: echo "This is the end!"
  
