name: Test reuseable workflow - USERNAME
run-name: Test reuseable workflow - USERNAME

on:
  workflow_dispatch:

jobs:
  call-greeting-workflow:
    # uses: ./.github/workflows/reusable-workflow.yml
    uses: training-test-tngx/gh-actions/.github/workflows/reusable-workflow.yml@main
    # uses: training-test-tngx/gh-actions/.github/workflows/reusable-workflow.yml@v1
    # uses: uses: training-test-tngx/gh-actions/.github/workflows/reusable-workflow.yml@SHA
    with:
      greeting: "Good morning"
      name: "My friend"
  another-job:
    runs-on: ubuntu-latest
    needs: call-greeting-workflow
    steps:
      - name: Show output
        run: echo "${{needs.call-greeting-workflow.outputs.greeting-text}}"
  
