name: Greet user workflow

on:
  workflow_call:
    inputs:
      greeting:
        required: true
        type: string
      name:
        required: true
        type: string
    outputs:
      greeting-text:
        value: ${{steps.last-step.outputs.result}}

jobs:
  greet-user:
    runs-on: ubuntu-latest
    outputs:
      result: ${{steps.last-step.outputs.output-from-step}}
    steps:
      - name: Say hello
        run: echo "${{inputs.greeting}}, ${{inputs.name}}!"
      - name: Ask how are you
        run: echo "How are you today, ${{inputs.name}}?"
      - name: Create output
        id: last-step
        run: echo "output-from-step=Have a good day, ${{inputs.name}}" >> $GITHUB_OUTPUT

