
####### This is a comment ###########

name: NEW!! 😊

run-name: '>>> MODIFIED WORKFLOW FROM BRANCH FEAT/C!!'

on:
 push:
  branches:
  - feat/*
 workflow_dispatch:
  inputs:
    name:
     description: 'Your name'
     required: true

jobs:
 hello-world:
  name: NEW HELLO WORLD JOB
  runs-on: ubuntu-latest
  steps:
   - name: Run Echo
     run: |
         echo "Guten Morgen ${{inputs.name}}!"
