name: Test Docker action - THANH
run-name: Test Docker action - THANH

on:
  workflow_dispatch:

jobs:
  greeting-job:
    runs-on: ubuntu-latest
    name: A job to greet someone
    steps:
      - uses: actions/checkout@v4
      - name: greeting action step
        id: greeting-step
        uses: ./ # use an action from the root directory
        with:
          greeting: "Good morning"
          name: "Thanh"
      - name: Show output from last step
        run: echo "${{ steps.greeting-step.outputs.greeting-text }}"
